import type { Post, User, ModerationQueueItem, ModerationStats } from "./types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    username: "sarahchen",
    displayName: "Sarah Chen",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    verified: true,
  },
  {
    id: "user-2",
    username: "mikejohnson",
    displayName: "Mike Johnson",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    verified: false,
  },
  {
    id: "user-3",
    username: "emilydavis",
    displayName: "Emily Davis",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    verified: true,
  },
  {
    id: "user-4",
    username: "alexrivera",
    displayName: "Alex Rivera",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    verified: false,
  },
  {
    id: "user-5",
    username: "jordanlee",
    displayName: "Jordan Lee",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    verified: true,
  },
]

export const mockPosts: Post[] = [
  {
    id: "post-1",
    author: mockUsers[0],
    content: "Just captured this amazing sunset at the beach. Nature never fails to amaze me! The colors were absolutely breathtaking today.",
    media: [
      {
        id: "media-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop",
        altText: "Sunset at the beach with orange and pink sky",
        aiDetection: {
          status: "authentic",
          confidence: 95,
          flags: [],
          analyzedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        },
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    likes: 1243,
    comments: 89,
    shares: 34,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "post-2",
    author: mockUsers[1],
    content: "Breaking: Major policy announcement expected tomorrow. Stay tuned for updates on this developing story.",
    media: [
      {
        id: "media-2",
        type: "image",
        url: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=600&fit=crop",
        altText: "Government building",
        aiDetection: {
          status: "under_review",
          confidence: 67,
          flags: ["Inconsistent lighting", "Metadata anomalies"],
          analyzedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
        },
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    likes: 5621,
    comments: 432,
    shares: 1205,
    isLiked: true,
    isBookmarked: true,
  },
  {
    id: "post-3",
    author: mockUsers[2],
    content: "This video has been circulating claiming to show a political figure making controversial statements. Our AI systems have flagged this as likely AI-generated.",
    media: [
      {
        id: "media-3",
        type: "video",
        url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop",
        thumbnailUrl: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop",
        altText: "Video thumbnail showing a speaker at podium",
        aiDetection: {
          status: "likely_ai",
          confidence: 89,
          flags: ["Audio inconsistencies", "Lip sync anomalies", "Deepfake patterns detected"],
          analyzedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
        },
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    likes: 234,
    comments: 567,
    shares: 89,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "post-4",
    author: mockUsers[3],
    content: "My morning coffee ritual. Simple pleasures make life beautiful.",
    media: [
      {
        id: "media-4",
        type: "image",
        url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
        altText: "Cup of coffee with latte art",
        aiDetection: {
          status: "authentic",
          confidence: 98,
          flags: [],
          analyzedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        },
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    likes: 892,
    comments: 45,
    shares: 12,
    isLiked: true,
    isBookmarked: false,
  },
  {
    id: "post-5",
    author: mockUsers[4],
    content: "This image claiming to show a protest in downtown has been confirmed as AI-generated by multiple detection systems. Please be aware of misinformation.",
    media: [
      {
        id: "media-5",
        type: "image",
        url: "https://images.unsplash.com/photo-1573152958734-1922c188fba3?w=800&h=600&fit=crop",
        altText: "Crowd scene",
        aiDetection: {
          status: "confirmed_ai",
          confidence: 97,
          flags: ["GAN artifacts detected", "Impossible geometry", "Duplicate faces", "Confirmed by manual review"],
          analyzedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
        },
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    likes: 156,
    comments: 892,
    shares: 2341,
    isLiked: false,
    isBookmarked: true,
  },
  {
    id: "post-6",
    author: mockUsers[0],
    content: "Weekend vibes at the park with friends. Perfect weather for a picnic!",
    media: [
      {
        id: "media-6",
        type: "image",
        url: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&h=600&fit=crop",
        altText: "People having a picnic in the park",
        aiDetection: {
          status: "authentic",
          confidence: 92,
          flags: [],
          analyzedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
        },
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    likes: 2156,
    comments: 134,
    shares: 67,
    isLiked: false,
    isBookmarked: false,
  },
]

export function getFilteredPosts(filter: "all" | "authentic" | "flagged"): Post[] {
  if (filter === "all") return mockPosts
  if (filter === "authentic") {
    return mockPosts.filter((post) =>
      post.media.every((m) => m.aiDetection.status === "authentic")
    )
  }
  return mockPosts.filter((post) =>
    post.media.some((m) => m.aiDetection.status !== "authentic")
  )
}

// Moderation queue data
export const mockModerationQueue: ModerationQueueItem[] = [
  {
    id: "mod-1",
    post: mockPosts[2], // The "likely_ai" video post
    flaggedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    priority: "critical",
    reportCount: 47,
    reportReasons: ["Deepfake content", "Political misinformation", "Impersonation"],
    status: "pending",
  },
  {
    id: "mod-2",
    post: mockPosts[4], // The "confirmed_ai" protest image
    flaggedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    priority: "high",
    reportCount: 23,
    reportReasons: ["AI-generated content", "Misleading context"],
    status: "pending",
  },
  {
    id: "mod-3",
    post: mockPosts[1], // The "under_review" government building
    flaggedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    priority: "medium",
    reportCount: 8,
    reportReasons: ["Suspicious metadata", "Unverified source"],
    status: "pending",
  },
  {
    id: "mod-4",
    post: {
      id: "post-flagged-1",
      author: mockUsers[3],
      content: "BREAKING: Leaked audio reveals secret government plans. Listen for yourself.",
      media: [
        {
          id: "media-flagged-1",
          type: "video",
          url: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&h=600&fit=crop",
          thumbnailUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&h=600&fit=crop",
          altText: "Audio waveform visualization",
          aiDetection: {
            status: "likely_ai",
            confidence: 92,
            flags: ["Voice cloning detected", "Audio splicing artifacts", "Unnatural pitch variations"],
            analyzedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
          },
        },
      ],
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      likes: 1893,
      comments: 456,
      shares: 789,
      isLiked: false,
      isBookmarked: false,
    },
    flaggedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    priority: "critical",
    reportCount: 156,
    reportReasons: ["Voice cloning", "Political manipulation", "Unverified claims"],
    status: "pending",
  },
  {
    id: "mod-5",
    post: {
      id: "post-flagged-2",
      author: mockUsers[1],
      content: "Exclusive footage from the rally yesterday. The crowd was massive!",
      media: [
        {
          id: "media-flagged-2",
          type: "image",
          url: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=600&fit=crop",
          altText: "Large crowd at a political rally",
          aiDetection: {
            status: "under_review",
            confidence: 73,
            flags: ["Crowd duplication patterns", "Inconsistent shadows", "EXIF data missing"],
            analyzedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
          },
        },
      ],
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      likes: 2341,
      comments: 189,
      shares: 567,
      isLiked: false,
      isBookmarked: false,
    },
    flaggedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    priority: "medium",
    reportCount: 12,
    reportReasons: ["Potentially manipulated image", "Exaggerated claims"],
    status: "pending",
  },
]

export const mockModerationStats: ModerationStats = {
  pending: mockModerationQueue.length,
  reviewedToday: 34,
  removedToday: 8,
  escalated: 3,
  avgReviewTime: "4m 23s",
}

export function getModerationQueue(priority?: "low" | "medium" | "high" | "critical"): ModerationQueueItem[] {
  if (!priority) return mockModerationQueue
  return mockModerationQueue.filter((item) => item.priority === priority)
}
